feat: check status and return result codes when placing an order
front-commerce/magento1-module-payline-front-commerce pull request #2
Opened 2021-03-31 09:01 UTC by real34

This PR adds a new important check when an order is placed.\
It reuses the code from the module to provide information about the order and transaction status (and update it accordingly in the database).

2021-03-31 10:34 UTC, dpobel requested changes
(weird to indent php with 2 spaces, but that's not specific to this PR)

2021-03-31 10:34 UTC, dpobel commented on app/code/community/FrontCommerce/Payline/Helper/Duplication.php
>          // Order should not be created exept from shortcut
1. commenting code is a very bad practice
1. the inline comment seems to be irrelevant now

2021-03-31 10:34 UTC, dpobel commented on app/code/community/FrontCommerce/Payline/Helper/Duplication.php
> +    }
it would be nice to put in an external methods for instance `isOrderAlreadyDone`
(also I guess `0` and `3` have a meaning, some constant would help)

2021-03-31 10:34 UTC, dpobel commented on app/code/community/FrontCommerce/Payline/Helper/Duplication.php
> +      return;
dead code :)

2021-03-31 10:34 UTC, dpobel commented on app/code/community/FrontCommerce/Payline/Helper/Duplication.php
> +      if (is_array($webPaymentDetails) and !empty($webPaymentDetails['transaction'])) {
there are way too many indent levels, I think those 2 conditions could easily be
inverted to return early and improve a bit the readability

2021-03-31 10:34 UTC, dpobel commented on app/code/community/FrontCommerce/Payline/Helper/Duplication.php
> +          }
maybe put in an external method `setOrderStatus` and `04003` would deserver its
own constant

2021-03-31 10:34 UTC, dpobel commented on app/code/community/FrontCommerce/Payline/Helper/Duplication.php
> +          }
same here dedicated method

2021-03-31 10:34 UTC, dpobel commented on app/code/community/FrontCommerce/Payline/Helper/Duplication.php
> +          if (!in_array($webPaymentDetails['result']['code'], $pendingCodes)) {
all that in a `isPendingPayment`

2021-03-31 10:34 UTC, dpobel commented on app/code/community/FrontCommerce/Payline/Helper/Duplication.php
> +            $tokenForUpdate->setStatus(3); // to be determined
put those 1, 2, 3 in a constant with a name (improves readability and avoids
those comment)

2021-04-01 06:53 UTC, real34 commented
As discussed internally, until now the code was mostly duplicated from the original module in a way that makes it "diff-able" to ease backporting fixes from upstream version.

Since the upstream module might not evolve much more from now on, we'll refactor the code a bit in an upcoming PR to make it more readable.

2021-04-01 06:54 UTC, merged